name: transparent_svg
description: A transparent svg image used in the same way as transparent_image
version: 1.0.0
homepage: https://github.com/SKLn-Rad

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
